remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

include: [docs]

exclude:
  - docs/html
  - docs/source
  - docs/doctrees
  - Makefile
  - docs/conf.py
  - test_media/sources

title: "ORI Annotations Documentation"
