remote_theme: just-the-docs/just-the-docs
color_scheme: dark
plugins:
- jekyll-remote-theme
- jekyll-seo-tag

include: [docs]

exclude:
  - docs/html
  - docs/source
  - docs/doctrees
  - Makefile
  - docs/conf.py
  - test_media/sources
  - openspec

title: "ORI Annotations Documentation"
